### ISSUE TITLE
rebuild is not triggered after updating the model, After Hot Restart

### ISSUE THREAD

**Issue by d3fkon** [xamantra/momentum#15]
This is a very absurd issue. The library works as expected first time, after building  the application.

But after I hot-restart the app, `.updateMomentum` doesn't seem to work. 
This is because, after the hot-restart, the logger says that there are no active listeners.  

It's a very simple application

app.controller.dart
```dart
class AppController extends MomentumController<AppModel> {
  @override
  AppModel init() {
    return AppModel(this);
  }

  @override
  Future<void> bootstrapAsync() async {
    return super.bootstrapAsync();
  }

  /// Add a new project to the project
  void addProject(Project project) {
    model.update(appProjects: model.appProjects..add(project));
  }
}

```

app.model.dart
```dart
class AppModel extends MomentumModel<AppController> {
  final List<Project> _appProjects;

  /// Getter for all the [_appProjects]
  List<Project> get appProjects => _appProjects.reversed.toList();

  /// Default constructor
  AppModel(AppController controller,
      {List<Project> appProjects = const <Project>[]})
      : _appProjects = []..addAll(appProjects.toList()),
        super(controller);

  @override
  void update({List<Project> appProjects = const []}) {
    AppModel(controller, appProjects: []..addAll(appProjects)).updateMomentum();
  }
}

```

main.dart
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SizeUtil().init(context);
    Dimens().init(context);
    return Momentum(
      controllers: <MomentumController<dynamic>>[
        AppController()..config(lazy: false),
        ProjectDetailController()
      ],
      services: [],
      enableLogging: true,
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.teal,
          visualDensity: VisualDensity.adaptivePlatformDensity,
        ),
        home: HomePage(),
      ),
    );
  }
}
```
This is how I update the state. The `addProject` method
```dart
  void addProject() {
    Momentum.controller<AppController>(context).addProject(defaultProject);
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton.extended(
        label: Text('NEW VIDEO LESSON'),
        icon: Icon(Icons.add),
        onPressed: addProject,
      ),
      body: MomentumBuilder(
        controllers: [AppController],
        builder: (context, snapshot) {
          final model = snapshot<AppModel>();
          return ListView(
            children: <Widget>[
              for (final project in model.appProjects)
                Card(
                  elevation: 4,
                  child: ListTile(
                    title: Text('${project.projectName}'),
                    subtitle: Text('${project.videos.length} Video(s)'),
                    trailing: Icon(Icons.video_call),
                  ),
                ),
                ...
                ...
                ... 
      ),
    );
```
------------------------------------------------------------------------------------------

After a **COMPLETE rebuild/restart**, and I hit the "Add Button"
```
I/flutter (21486): [Momentum -> 'AppController'] the model "AppModel" has been updated, listeners => ACTIVE: 1 (notified), INACTIVE: 0 (ignored)
```
After a **HOT RESTART**, and I hit the "Add Button"
```
I/flutter (21486): [Momentum -> 'AppController'] the model "AppModel" has been updated, listeners => ACTIVE: 0 (notified), INACTIVE: 0 (ignored)
```

This is really frustrating. I really liked this architecture. Can anyone tell me what I'm doing wrong?

**Comment by d3fkon** [comment]
Okay, I as I see it, moving my MomentumBuilder outside the Scaffold and using `snapshot<T>().controller` to update the model , fixed this issue.
```dart
onPressed: () {
              snapshot<AppModel>().controller.addProject(defaultProject);
            },
```

The bug is clearly in accessing the controller.
The following seems to consistently fail after each hot restart
```dart
Momentum.controller<AppController>(context).addProject(defaultProject);
```
Looks like momentum controllers accessed with context, updates the model, but removes the listener (only after a Hot Restart).
I don't think I understand why this is happening

**Comment by xamantra** [comment]
You are confusing **hot restart** and **hot reload** please edit the title of this issue. You are experiencing this issue during a hot reload.

**BUG:** The hierarchy of your `MyApp` and `Momentum` widget is wrong. Momentum should always be the root of your app. In your case, MyApp is the root, and Momentum is being returned in the build method. [Docs: Momentum must be the root widget of your app](https://xamdev.gq/momentum/#/momentum?id=momentum).

Try to follow this code in your `main.dart` file:
```dart
void main() {
  runApp(
    Momentum(
      controllers: [
        AppController()..config(lazy: false),
        // ProjectDetailController(),
      ],
      services: [],
      enableLogging: true,
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // SizeUtil().init(context);
    // Dimens().init(context);
    return MaterialApp(
      title: 'Momentum State Management',
      theme: ThemeData(
        primarySwatch: Colors.teal,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      debugShowCheckedModeBanner: false,
      home: HomePage(), // we're gonna create this later...
    );
  }
}
```
- I commented the lines out that I can't reproduce. They don't seem to affect how momentum works anyway.
- Now, try to test the app after both **hot restart** and **hot reload**.

If something is still wrong with the behavior after correcting the hierarchy, try to follow the guide below:

#### Miscellaneous
**First**, your `AppModel` is written weirdly. The `update()` method doesn't follow the `copyWith()` [method convention](https://xamdev.gq/momentum/#/momentum-model?id=update). The private `_addProjects` final property. You don't need to make the properties private because they are required to be final. The constructor is written weirdly too, it should just be a simple constructor.

Follow this code in your model file:
```dart
class AppModel extends MomentumModel<AppController> {
  AppModel(
    AppController controller, {
    this.appProjectsList,
  }) : super(controller);

  final List<Project> appProjectsList;

  /// Getter for all the [appProjectsList]. Reversed.
  List<Project> get appProjects => appProjectsList.reversed.toList();

  @override
  void update({
    List<Project> appProjectsList,
  }) {
    AppModel(
      controller,
      appProjectsList: appProjectsList ?? this.appProjectsList,
    ).updateMomentum();
  }
}
```

<br>

**Second**, the `addProject(...)` method inside your controller might cause a bug. If I get it right, you want to add a project into the list when the add button gets clicked? When working with a list in immutable classes, it is not recommended to modify the list directly from the model. You must create a copy and modify that.

Follow this code in your controller file:
```dart
class AppController extends MomentumController<AppModel> {
  @override
  AppModel init() {
    return AppModel(
      this,
      appProjectsList: [], // empty list as default value.
    );
  }

  @override
  Future<void> bootstrapAsync() async {
    return super.bootstrapAsync();
  }

  /// Add a new project to the project
  void addProject(Project project) {
    var newList = List<Project>.from(model.appProjects)..add(project);
    model.update(appProjectsList: newList);
  }
}
```

Your `HomePage` code is fine. This code should also work fine by the way:
```dart
  void addProject() {
    Momentum.controller<AppController>(context).addProject(defaultProject);
  }
```

**Comment by d3fkon** [comment]
You are right making `Momentum` the root of my application fixed the issue. Thanks for the advice too
