### ISSUE TITLE
Add support for RouteSettings in the Router & how do we deal w/ screen constructors w/ Routers?

### ISSUE THREAD

**Issue by exts** [xamantra/momentum#16]
Currently there's two ways you would probably want to pass data to a route. Say you have a new todo item that belongs to a category. Maybe you want to create a separate page screen for adding that todo item to said category. Instead of redirecting to an empty constructor you might want to initialize that constructor by passing the category id, but a category isn't required so maybe sometimes you won't add a todo item to a parent id at all and no constructor initialization is needed. The other way would be just passing basic data to the build method using RouteSettings when traveling to another page for instance displaying the results from the previous page's calculations. 

`Router.goto(context, AddItemScreen)` is the default way to do this with Momentum which is great, simple love it. Maybe there's optional named arguments though in that screen class that takes a value. Currently there's no way to pass data to that. Not sure what the cleanest way to do it would be, but I do know `Function.apply` is a thing, not sure how you would do it for constructors though.

```dart
void main() {
  var hmm = Function.apply(Test.init, ["hey"]);
  print(hmm.data);
}


class Test {
  String data;
  Test({this.data});
  static Test init(String data) {
    return Test(data: data);
  }
}
```

As for RouteSettings, that seems like that could just be passed to the MaterialPageRoute that gets created. I wouldn't mind submitting a PR for RouteSettings support later this week if you don't get to it, but the other constructor stuff is interesting and would be a lovely feature.

**Comment by xamantra** [comment]
I created momentum in mind that I don't need constructor data params in my pages. In the old docs (which is gone already), I mentioned there that one of the focus in momentum is parameterless widgets. If you try to dig into [Listify example app](https://github.com/xamantra/listify), you'll see that the `Add List Screen` (which is also used for editing lists), doesn't have any parameters in the constructor. So how does editing of the list works? Simple, take a look at this code taken from Listify example app:

The edit button [code](https://github.com/xamantra/listify/blob/0777c9cf3941fc77abe75da1d8dd20221c98081c/lib/src/pages/view-list.dart#L67):
```dart
onPressed: () {
  listController.editList(listName);
  Router.goto(context, AddNewList);
  // Imagine this code as equivalent to:
  // Navigator.push(context, MaterialPageRoute(builder: (context) => AddNewList(listName: listName)));
},
```
As you can see, we are setting data before we actually go to a specific page.

But, your proposal is still possible, I'm thinking of adding an optional parameter in the `Router.goto` function for passing parameters and accessing them using a generic method.

The params model class:
```dart
class AddNewListParams {
  final String listName;
  AddNewListParams(this.listName);
}
```

The route parameter:
```dart
onPressed: () {
  // listController.editList(listName);
  // Router.goto(context, AddNewList);
  Router.goto(context, AddNewList, param: AddNewListParams(listName));
},
```

Accessing the route parameter using:
```dart
// static method
Router.getParams<AddNewListParams>(context);
```

Accessing from inside a controller:
```dart
var router = getService<Router>();
var listName = router.getParams<AddNewListParams>().listName;
```

In this concept, the pages will still be parameterless, the parameters are reusable from both widget and controller, and this is also a non-breaking change for existing projects.

Yeah, this is very possible. I will try to get into this later. Thanks for the suggestion.

**Comment by exts** [comment]
Going to check out your todo example again and yeah I like the params, but maybe add a little sugar so you can just do something like `Router.getParams<AddNewListParams>()`

**Comment by xamantra** [comment]
Oh, wait. I think this is better. Inside `MomentumController` we have built-in methods:
- `dependOn<T>` - for accessing other controllers.
- `getService<T>` - for accessing services.

I think I can do:
```dart
void someMethod() {
  var params = getParams<AddNewListParams>();
  // or "getRouterParams<T>()"...
  var listName = params.listName;
  var otherParam = params.otherParam;
}
```

**Comment by xamantra** [comment]
Just a follow-up comment.

I started coding this one. And I realized that it is bigger than expected because:
- Persistence needs to be considered. *(Optionally enable or disable)*.
- The `getParams<T>()` inside controllers need to be decoupled instead of adding directly inside `MomentumController` as a built-in function. *(I created `RouterMixin` for MomentumController instead)*. It is bad design if from widgets you are able to call `someController.getParams<T>()` without context and it looks like the params are from the controller, not the router. This means that the `getParams<T>()` method doesn't really exist for all controllers by default. You need to do this:

  ```dart
  // from:
  class SomeController extends MomentumController { ... }

  // to:
  class SomeController extends MomentumController with RouterMixin { ... }
  ```
- I decided to add the `enablePersistence` parameter on the `Router` constructor to optionally disable it. So you can still use momentum's built-in router system without persistence. *(I realized I don't always need it)*.
- I'll be adding new tests and docs too.

I don't know when will I be done with this because it's quite busy. This feature is really cool.

**Comment by drago-vlc** [comment]
ql tnx

**Comment by xamantra** [comment]
Ok so, the persistence support for route param is harder than I expected. The reason is that the route param can be of any type so the JSON serializer will not know exactly what type it will need to serialize. I will still implement the route parameter.

If the developer wants to persist the parameter, they only need to put the param on the model too and enable persistence on that model.

**Comment by xamantra** [comment]
I published a new version on pub.dev: [v1.2.8](https://pub.dev/packages/momentum/changelog#128)

Docs References:
  - Updated `Router.goto` and `Router.pop` [docs](https://xamdev.gq/momentum/#/router?id=goto).
  - New `RouterMixin` [docs](https://xamdev.gq/momentum/#/router_mixin).

**Comment by xamantra** [comment]
@exts if you found an issue relating to this update, file a separate issue. I'll be locking this one.
