### ISSUE TITLE
Consider adding alias to Momentum.of<Controller>()

### ISSUE THREAD

**Issue by SaurabhSM** [xamantra/momentum#2]
Hi,

It would be consistent if there is alias for `Momentum.of<ControllerName>() ` to `controller<ControllerName>(context);`

**Comment by xamantra** [comment]
I've been actually thinking about this long ago. The reason I use `.of<T>` was to follow the traditional way of naming it and `of` looks cute and it's easier to type :)

Maybe I'll add this alias on next release. I'm also thinking if I should go with `controller<T>` or `getController<T>` because we currently have `getService<T>`.

**Comment by SaurabhSM** [comment]
I personally think, it's easier to confuse getController<T> as user defined function as usually most of the devs use getXYZ. `controller<T>` or `snapshot<T>` and 'service<T>` could easily identify it is part of package instead of user defined function.

**Comment by xamantra** [comment]
Thanks for the idea, I'll consider it.

**Comment by xamantra** [comment]
This suggestion was included in the new release, [v1.1.7](https://pub.dev/packages/momentum/versions/1.1.7)

API Reference for [Momentum.controller\<T\>(context)](https://xamdev.gq/momentum/#/momentum?id=controllerlttgtcontext)
and for [Momentum.service\<T\>(context)](https://xamdev.gq/momentum/#/momentum?id=servicelttgtcontext)
