### ISSUE TITLE
Dependency injection is flawed.

### ISSUE THREAD

**Issue by KalilDev** [xamantra/momentum#5]
Having dependency injection would be good for creating mock controllers or hiding the implementation details, but as it stands, this can't be done. Momentum uses Object.runtimeType, which does not account for Mixing, Implementing or Extending classes, and is unsafe on dart2js in some scenarios. The functions that use Object.runtimeType should be refactored to use 'foo is T', and the places that should be refactored are Momentum._validateControllers, Momentum._getControllerOfType. Additionally, not related to the DI, Router._goto should also be refactored for the same reason.

**Comment by KalilDev** [comment]
The remaining usages of Object.runtimeType, which are for logging and stuff are fine.

**Comment by xamantra** [comment]
Okay so after some testing. I figure out that `foo is T` is the bug, not `runtimeType`.

Take a look at this:

### Sample script:
You can also run it on [dartpad.dev](https://dartpad.dev/f70d8af6edb3bd5a0da4b2e299faebd4)

```dart
Type type<T>() => T;

class Settings {
  // logic here ...
}

class ASettings extends Settings {
  // logic here ...
}

class BSettings extends ASettings {
  // logic here ...
}

var _settings = Settings();
var _aSettings = ASettings();
var _bSettings = BSettings();

void main() {
  print('using "foo is T":\n');
  fooIsT();
  print('\n\nusing "runtimeType == Type":\n');
  objectRuntimeType();
}

void fooIsT() {
  print('$Settings is $ASettings => ${_settings is ASettings}');
  print('$ASettings is $Settings => ${_aSettings is Settings}');
  print('$Settings is $BSettings => ${_settings is BSettings}');
  print('$BSettings is $Settings => ${_bSettings is Settings}');
  print('$ASettings is $BSettings => ${_aSettings is BSettings}');
  print('$BSettings is $ASettings => ${_bSettings is ASettings}');
}

void objectRuntimeType() {
  print('$Settings == $ASettings => ${_settings.runtimeType == type<ASettings>()}');
  print('$ASettings == $Settings => ${_aSettings.runtimeType == type<Settings>()}');
  print('$Settings == $BSettings => ${_settings.runtimeType == type<BSettings>()}');
  print('$BSettings == $Settings => ${_bSettings.runtimeType == type<Settings>()}');
  print('$ASettings == $BSettings => ${_aSettings.runtimeType == type<BSettings>()}');
  print('$BSettings == $ASettings => ${_bSettings.runtimeType == type<ASettings>()}');
  print('\ncorrect types:\n');
  print('$Settings == $Settings => ${_settings.runtimeType == type<Settings>()}');
  print('$ASettings == $ASettings => ${_aSettings.runtimeType == type<ASettings>()}');
  print('$BSettings == $BSettings => ${_bSettings.runtimeType == type<BSettings>()}');
}
```

The output of the script is this:
```bash
using "foo is T":

Settings is ASettings => false
ASettings is Settings => true
Settings is BSettings => false
BSettings is Settings => true
ASettings is BSettings => false
BSettings is ASettings => true


using "runtimeType == Type":

Settings == ASettings => false
ASettings == Settings => false
Settings == BSettings => false
BSettings == Settings => false
ASettings == BSettings => false
BSettings == ASettings => false

correct types:

Settings == Settings => true
ASettings == ASettings => true
BSettings == BSettings => true
```

### Breaking it down:

<hr>

Now first, let's take a look at `foo is T`'s last result:
- `BSettings is ASettings => true`

Applying this in momentum:
```dart
var bController = Momentum.controller<BController>(context);
```

`BController` can also be `AController`, this is very bugged and it should never return `AController`.

<hr>

What **I** want personally on my projects and what **I** want with momentum to do is this:

Let's take `runtimeType == Type`'s last result:
- `BSettings == ASettings => false`

Now as you can see because this is `false`, `Momentum.controller<BController>` will never return `AController`. And that's what I want.

<hr>

It is the same as the `Router`. If you have `PageB` that extends `PageA`, and you called `Router.goto(context, PageB)`, you will be redirected to `PageA` instead. `PageB is PageA` returns `true`.

The test files are in these locations:
- `test\types_test.dart`
- `test\types_one_builder_test.dart`
- `test\widgets\types_test_widget.dart` - the controllers has their own `MomentumBuilder`.
- `test\widgets\types_test_widget_one_builder.dart` - all the controllers are injected only into one `MomentumBuilder`.
- `test\widgets\types_test_widget_one_builder_error.dart` - error test for extending controllers.
- `test\components\types-test\` - the controllers and models are here. Includes abstract, mixin, extends, and implements.

The original issue was changing `runtimeType` checks into `foo is T`. But when testing multiple cases, `foo is T` ended up becoming the bug. I have fixed this issue and refactored all type checks into runtimeType. I left `router is Router` unchanged because you will only want 1 router to be injected into services anyway.

I will close this issue now but feel free to reopen it if you have some cases that can invalidate these tests.
